steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/tafsir-simplified/tafsir-backend:latest',
    '--file', 'backend/Dockerfile',
    './backend'
  ]
images:
- 'gcr.io/tafsir-simplified/tafsir-backend:latest'
options:
  logging: CLOUD_LOGGING_ONLY
